server:
  port: ${PORT:${SERVER_PORT:0}}

info:
  id: ${spring.application.name}

debug: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}}/eureka/

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:${APPLICATION_DOMAIN:localhost}}
    nonSecurePort: 80
