server:
  port: ${PORT:${SERVER_PORT:0}}

info:
  id: ${spring.application.name}

debug: true




spring:
  sleuth:
    log:
      json:
        enabled: true

logging:
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wex'



---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:${APPLICATION_DOMAIN:localhost}}
    nonSecurePort: 80
